//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventorySystemEntities : DbContext
    {
        public InventorySystemEntities()
            : base("name=InventorySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<inventoryTransaction> inventoryTransactions { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productDetail> productDetails { get; set; }
        public DbSet<purchaseOrder> purchaseOrders { get; set; }
        public DbSet<purchaseOrderLine> purchaseOrderLines { get; set; }
        public DbSet<saleOrder> saleOrders { get; set; }
        public DbSet<saleOrderLine> saleOrderLines { get; set; }
        public DbSet<subCategory> subCategories { get; set; }
    }
}
