//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryTransaction
    {
        public int itID { get; set; }
        public int productDetailsID { get; set; }
        public int startingQuantity { get; set; }
        public int currentQuantity { get; set; }
        public int minimumQuantity { get; set; }
    
        public virtual productDetail productDetail { get; set; }
    }
}
