//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventorySystemEntities2 : DbContext
    {
        public InventorySystemEntities2()
            : base("name=InventorySystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<inventoryTransaction> inventoryTransactions { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productDetail> productDetails { get; set; }
        public virtual DbSet<purchaseOrder> purchaseOrders { get; set; }
        public virtual DbSet<purchaseOrderLine> purchaseOrderLines { get; set; }
        public virtual DbSet<saleOrder> saleOrders { get; set; }
        public virtual DbSet<saleOrderLine> saleOrderLines { get; set; }
        public virtual DbSet<subCategory> subCategories { get; set; }
    }
}
