//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productDetail()
        {
            this.inventoryTransactions = new HashSet<inventoryTransaction>();
            this.purchaseOrderLines = new HashSet<purchaseOrderLine>();
            this.saleOrderLines = new HashSet<saleOrderLine>();
        }
    
        public int pdid { get; set; }
        public int productID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> bprice { get; set; }
        public Nullable<decimal> sprice { get; set; }
        public Nullable<decimal> discountAllowed { get; set; }
        public decimal discountReceived { get; set; }
        public byte[] date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryTransaction> inventoryTransactions { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchaseOrderLine> purchaseOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saleOrderLine> saleOrderLines { get; set; }
    }
}
