//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseOrderLine
    {
        public int polID { get; set; }
        public int purchaseOrderID { get; set; }
        public int productDetailsID { get; set; }
        public int Quantity { get; set; }
        public decimal buyingPrice { get; set; }
    
        public virtual productDetail productDetail { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
    }
}
