//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleOrderLine
    {
        public int solID { get; set; }
        public int saleOrderID { get; set; }
        public int productDetailsID { get; set; }
        public int quantity { get; set; }
        public decimal sellingPrice { get; set; }
    
        public virtual productDetail productDetail { get; set; }
        public virtual saleOrder saleOrder { get; set; }
    }
}
